export const logins = [
  {
    escola: "Escola Patelli",
    email: "paula@escolapatelli.com.br",
    equipe1: "Patelli 1 -  Escola Patelli",
    passou1: false,
    senha1: "cd92",
    equipe2: "",
    passou2: false,
    senha2: "",
    link: "https://us06web.zoom.us/j/89419773531",
  },
  {
    escola: "CDJ EDUCACIONAL",
    email: "douglasvaladares@cdjeducacional.com",
    equipe1: "Arquimisticos-CDJ EDUCACIONAL",
    passou1: false,
    senha1: "gh78",
    equipe2: "Corujas - CDJ EDUCACIONAL",
    passou2: false,
    senha2: "ij90",
    link: "https://us06web.zoom.us/j/89419773531",
  },
  {
    escola: "Associação Educacional Betel Brasileiro",
    email: "damaris.navarro@colegiobetelbrasileiro.com",
    equipe1: "Equipe Alfa - Betel Brasileiro",
    passou1: false,
    senha1: "ef56",
    equipe2: "Betel Brasileiro -EQUIPE DELTA",
    passou2: false,
    senha2: "sf38",
    link: "https://us06web.zoom.us/j/89419773531",
  },
  {
    escola: "Colégio FEB",
    email: "joao.guimaraes@unifeb.edu.br",
    equipe1: "ColegioFeb 01 -Colégio FEB",
    passou1: false,
    senha1: "op12",
    equipe2: "ColegioFeb 03- Colégio FEB",
    passou2: false,
    senha2: "qr34",
    link: "https://us06web.zoom.us/j/89419773531",
  },
  {
    escola: "Colégio Sagrado Coração de Jesus",
    email: "cscjcoordmedio@gmail.com",
    equipe1: "ALFA -Sagrado Coração de Jesus",
    passou1: false,
    senha1: "ef79",
    equipe2: "THETA  - Sagrado Coração de Jesus",
    passou2: false,
    senha2: "cd68",
    link: "https://us06web.zoom.us/j/89419773531",
  },
  {
    escola: "EDUCATIVA OURINHOS",
    email: "coordenacaof2@educativace.com.br",
    equipe1: "DDE - EDUCATIVA OURINHOS",
    passou1: false,
    senha1: "wx69",
    equipe2: "Sharp Minds - Educativa Ourinhos",
    passou2: false,
    senha2: "yz70",
    link: "https://us06web.zoom.us/j/89419773531",
  },
  {
    escola: "COLÉGIO FANTÁSTICO",
    email: "fundamental.cfant@gmail.com",
    equipe1: "Camaleão Neuróticos- Colégio Fantastico",
    passou1: false,
    senha1: "kl89",
    equipe2: "Sexteto Fantástico- - Colégio Fantastico",
    passou2: false,
    senha2: "mn01",
    link: "https://us06web.zoom.us/j/89419773531",
  },
  {
    escola: "INSTITUTO XAVIER",
    email: "victoriapaula565@gmail.com",
    equipe1: "Matemágicos - INSTITUTO XAVIER",
    passou1: true,
    senha1: "kl37",
    equipe2: "Os Revolucionários - INSTITUTO XAVIER",
    passou2: false,
    senha2: "mn48",
    link: "https://us06web.zoom.us/j/89419773531",
  },
  {
    escola: "Colégio Sorocaba",
    email: "anaquezia.ferraz@colegiosorocaba.com.br",
    equipe1: "Equipe 3- Colégio Sorocaba",
    passou1: false,
    senha1: "qr36",
    equipe2: "A Tropa do Enigma -Colégio Sorocaba",
    passou2: false,
    senha2: "op25",
    link: "https://us06web.zoom.us/j/89419773531",
  },
  {
    escola: "Colégio Monteiro Lobato",
    email: "contato@colegiomlobato.com.br",
    equipe1: "Monteiro 1- Monteiro Lobato",
    passou1: false,
    senha1: "kl77",
    equipe2: "Monteiro 2- Monteiro Lobato",
    passou2: false,
    senha2: "mn88",
    link: "https://us06web.zoom.us/j/89419773531",
  },
  {
    escola: "Escola Pilar",
    email: "thiara@pilarjarinu.com.br",
    equipe1: "Júpiter - Escola Pilar",
    passou1: false,
    senha1: "ef03",
    equipe2: "Mercúrio - Escola Pilar",
    passou2: true,
    senha2: "gh15",
    link: "https://us06web.zoom.us/j/89419773531",
  },
  {
    escola: "COLÉGIO GRADUAL TIETÊ",
    email: "coordenacao@colegiogradual.com.br",
    equipe1: "GRADUAL  - GRADUAL TIETÊ",
    passou1: false,
    senha1: "st56",
    equipe2: "",
    passou2: false,
    senha2: "",
    link: "https://us06web.zoom.us/j/89419773531",
  },
  {
    escola: "Colégio Alpis Veredas",
    email: "protiagobarros@gmail.com",
    equipe1: "Alpis Veredas 1- Alpis Veredas",
    passou1: false,
    senha1: "mn22",
    equipe2: "Alpis Veredas 3- Alpis Veredas",
    passou2: false,
    senha2: "op33",
    link: "https://us06web.zoom.us/j/89419773531",
  },
  {
    escola: "Anjo da Guarda São Rafael",
    email: "tdiasm@gmail.com",
    equipe1: "Fernanda Metálica - Anjo da Guarda",
    passou1: false,
    senha1: "ab12",
    equipe2: "Onça Pint*da- Anjo da Guarda",
    passou2: true,
    senha2: "cd34",
    link: "https://us06web.zoom.us/j/89419773531",
  },
  {
    escola: "Colégio e Curso Conexão",
    email: "coordenacao@colegioecursoconexao.com.br",
    equipe1: "Liga X - Conexão",
    passou1: false,
    senha1: "ef23",
    equipe2: "",
    passou2: false,
    senha2: "",
    link: "https://us06web.zoom.us/j/89419773531",
  },
  {
    escola: "ESCOLA INTERATIVA",
    email: "sandrapmancini@gmail.com",
    equipe1: "Neurônios em Ação - Escola Interativa",
    passou1: false,
    senha1: "ab81",
    equipe2: "",
    passou2: false,
    senha2: "",
    link: "https://us06web.zoom.us/j/89419773531",
  },
  {
    escola: "Colégio Associação de Ensino Guararapes",
    email: "crisgrp@hotmail.com",
    equipe1: "Araucária - Guararapes",
    passou1: true,
    senha1: "qr44",
    equipe2: "Aroeira- Guararapes",
    passou2: false,
    senha2: "st55",
    link: "https://us06web.zoom.us/j/89419773531",
  },
  {
    escola: "Colégio Oficina do Estudante",
    email: "direcaocolegio@oficinadoestudante.com.br",
    equipe1: "Oficina do Estudante -  Equipe - Brasil",
    passou1: false,
    senha1: "op99",
    equipe2: "Oficina do Estudante -  Equipe Paineiras",
    passou2: false,
    senha2: "qr00",
    link: "https://us06web.zoom.us/j/89419773531",
  },
  {
    escola: "Colégio Batista de Santarém",
    email: "maria_dasgracas35@hotmail.com",
    equipe1: "Amarelo - Batista de Santarém",
    passou1: false,
    senha1: "wx77",
    equipe2: "Verde - Batista de Santarém",
    passou2: false,
    senha2: "yz88",
    link: "https://us06web.zoom.us/j/89419773531",
  },
  {
    escola: "Colégio Carlos Drummond de Andrade",
    email: "coordenacao03@ccda.com.br",
    equipe1: "Lirius-  CCDA",
    passou1: false,
    senha1: "uv82",
    equipe2: "Girassol- CCDA",
    passou2: false,
    senha2: "wx93",
    link: "https://us06web.zoom.us/j/89419773531",
  },
  {
    escola: "CENTRO EDUCACIONAL CRISTÃO",
    email: "guilhermecarmello@colegioceduc.com.br",
    equipe1: "The Thundermans- C E. CRISTÃO",
    passou1: true,
    senha1: "kl11",
    equipe2: "Curimbatá - C E. CRISTÃO",
    passou2: true,
    senha2: "ef38",
    link: "https://us06web.zoom.us/j/89419773531",
  },
  {
    escola: "Colégio Luminous Sol",
    email: "marcela.braganholo@gmail.com",
    equipe1: "Soul - Colégio Luminous Sol",
    passou1: true,
    senha1: "ef44",
    equipe2: "Ilumina - Colégio Luminous Sol",
    passou2: true,
    senha2: "cd33",
    link: "https://us06web.zoom.us/j/89419773531",
  },
  {
    escola: "COLÉGIO PROFESSOR ANTÔNIO BARROS",
    email: "guilherme.vasconcelos@pabescola.com.br",
    equipe1: "ELITE - Colégio P. Ant. BARROS",
    passou1: false,
    senha1: "uv24",
    equipe2: "",
    passou2: false,
    senha2: "",
    link: "https://us06web.zoom.us/j/89419773531",
  },
  {
    escola: "Teresa de Calcutá",
    email: "cris.golz@terra.com.br",
    equipe1: "Menos é menos - Teresa de Calcutá",
    passou1: false,
    senha1: "op59",
    equipe2: "Brain - Teresa de Calcutá",
    passou2: false,
    senha2: "qr60",
    link: "https://us06web.zoom.us/j/89419773531",
  },
  {
    escola: "Colégio Sistema",
    email: "sec@colsistema.com.br",
    equipe1: "Arara-Azul -  Colégio Sistema",
    passou1: true,
    senha1: "kl02",
    equipe2: "Onça-Pintada - Colégio Sistema",
    passou2: true,
    senha2: "mn14",
    link: "https://us06web.zoom.us/j/89419773531",
  },
  {
    escola: "Instituto Educacional Coração de Maria",
    email: "canal.coordenacao@iecoracaodemaria.com.br",
    equipe1: 'Coração de Maria" 2025- Colégio Maria',
    passou1: false,
    senha1: "ij26",
    equipe2: "",
    passou2: false,
    senha2: "",
    link: "https://us06web.zoom.us/j/89419773531",
  },
  {
    escola: "Colégio Primar",
    email: "katiajoyceguedes@hotmail.com",
    equipe1: "Colégio Primar -   Decifradores Primar",
    passou1: false,
    senha1: "st13",
    equipe2: "",
    passou2: false,
    senha2: "",
    link: "https://us06web.zoom.us/j/89419773531",
  },
  {
    escola: "COLÉGIO PURIFICAÇÃO",
    email: "mj-oliveira2012@hotmail.com",
    equipe1: "OS GREGOS - COLÉGIO PURIFICAÇÃO",
    passou1: true,
    senha1: "yz46",
    equipe2: "OS ROMANOS - COLÉGIO PURIFICAÇÃO",
    passou2: false,
    senha2: "ab57",
    link: "https://us06web.zoom.us/j/89419773531",
  },
  {
    escola: "Oliveira Ferreira",
    email: "prof.valdirsantos@gmail.com",
    equipe1: "COF - Oliveira Ferreira",
    passou1: false,
    senha1: "st71",
    equipe2: "",
    passou2: false,
    senha2: "",
    link: "https://us06web.zoom.us/j/89419773531",
  },
  {
    escola: "Colégio ENAU",
    email: "coordenacao.enau@colegioenau.com.br",
    equipe1: "Oráculo do Etapa- Colégio Enau",
    passou1: false,
    senha1: "gh45",
    equipe2: "Mestres do Enigma - Colégio Enau",
    passou2: false,
    senha2: "ij67",
    link: "https://us06web.zoom.us/j/89419773531",
  },
  {
    escola: "Colégio Integrado Belém Ltda",
    email: "yussefayan@colegioin.com",
    equipe1: "MUNDURUKU- Integrado Belém",
    passou1: false,
    senha1: "ab22",
    equipe2: "Tpinan-Integrado Belém",
    passou2: false,
    senha2: "yz11",
    link: "https://us06web.zoom.us/j/89419773531",
  },
  {
    escola: "Colégio Iguatemy",
    email: "everton.jose@iguatemy.com.br",
    equipe1: "Decifraloucos - Colégio Iguatemy",
    passou1: false,
    senha1: "uv78",
    equipe2: "Os Sherlock -  Colégio Iguatemy",
    passou2: false,
    senha2: "wx90",
    link: "https://us06web.zoom.us/j/89419773531",
  },
  {
    escola: "Colégio Unisuz",
    email: "daniel.fernandez@colegiounisuz.com.br",
    equipe1: "Alexandrinos -  Colégio Unisuz",
    passou1: true,
    senha1: "uv58",
    equipe2: "Gambistas - Colégio Unisuz",
    passou2: false,
    senha2: "st47",
    link: "https://us06web.zoom.us/j/89419773531",
  },
  {
    escola: "Colégio Magistra",
    email: "magistraprofessores@colegiomagistra.com.br",
    equipe1: "Magistrados - Colégio Magistra",
    passou1: false,
    senha1: "ij66",
    equipe2: "Nerdolas do Magistra- Colégio Magistra",
    passou2: false,
    senha2: "gh55",
    link: "https://us06web.zoom.us/j/89419773531",
  },
  {
    escola: "Colégio Santa Marta",
    email: "cristinal72@yahoo.com.br",
    equipe1: "Half a dozen - Colégio Santa Marta",
    passou1: true,
    senha1: "ij91",
    equipe2: "Kaleje",
    passou2: true,
    senha2: "",
    link: "https://us06web.zoom.us/j/89419773531",
  },
  {
    escola: "Colégio Atibaia",
    email: "colati@colegioatibaia.com.br",
    equipe1: "Athena - Atibaia",
    passou1: true,
    senha1: "uv66",
    equipe2: "OS 00 - Atibaia",
    passou2: true,
    senha2: "cd27",
    link: "https://us06web.zoom.us/j/89419773531",
  },
  {
    escola: "COLÉGIO BRASILIS",
    email: "raphaelmelo@colegiobrasilis.com.br",
    equipe1: "Desafiadores de limites - Brasilis",
    passou1: true,
    senha1: "ab99",
    equipe2: "Esquadrão dos Enigmas - Brasilis",
    passou2: true,
    senha2: "cd00",
    link: "https://us06web.zoom.us/j/89419773531",
  },
  {
    escola: "COLÉGIO BRASILIS",
    email: "oseias@colegiobrasilis.com.br",
    equipe1: "Aliança do Enigma - Brasilis",
    passou1: false,
    senha1: "",
    equipe2: "Oráculo Sigma - Brasilis",
    passou2: false,
    senha2: "",
    link: "https://us06web.zoom.us/j/89419773531",
  },
];
