export const logins = [
  // {
  //   escola: "Escola Patelli",
  //   email: "paula@escolapatelli.com.br	",
  //   equipe1: "Patelli 2",
  //   senha1: "cd92",
  //   equipe2: "",
  //   senha2: "",
  // },
  // {
  //   escola: "CDJ EDUCACIONAL",
  //   email: "douglasvaladares@cdjeducacional.com",
  //   equipe1: "ARQUIMISTICOS",
  //   senha1: "gh78",
  //   equipe2: "CORUJAS",
  //   senha2: "ij90",
  // },
  // {
  //   escola: "Associação Educacional Betel Brasileiro",
  //   email: "damaris.navarro@colegiobetelbrasileiro.com",
  //   equipe1: "Equipe Alfa",
  //   senha1: "ef56",
  //   equipe2: "EQUIPE DELTA",
  //   senha2: "sf38",
  // },
  // {
  //   escola: "Colégio FEB",
  //   email: "joao.guimaraes@unifeb.edu.br",
  //   equipe1: "ColegioFeb 01",
  //   senha1: "op12",
  //   equipe2: "ColegioFeb 03",
  //   senha2: "qr34",
  // },
  // {
  //   escola: "Colégio Sagrado Coração de Jesus",
  //   email: "cscjcoordmedio@gmail.com",
  //   equipe1: "ALFA",
  //   senha1: "ef79",
  //   equipe2: "THETA",
  //   senha2: "cd68",
  // },
  // {
  //   escola: "EDUCATIVA OURINHOS",
  //   email: "coordenacaof2@educativace.com.br",
  //   equipe1: "DDE",
  //   senha1: "wx69",
  //   equipe2: "Sharp Minds",
  //   senha2: "yz70",
  // },
  // {
  //   escola: "COLÉGIO FANTÁSTICO",
  //   email: "fundamental.cfant@gmail.com",
  //   equipe1: "CAMALEÃO NEURÓTICOS",
  //   senha1: "kl89",
  //   equipe2: "SEXTETO FANTÁSTICO",
  //   senha2: "mn01",
  // },
  // {
  //   escola: "INSTITUTO XAVIER",
  //   email: "victoriapaula565@gmail.com",
  //   equipe1: "Matemágicos",
  //   senha1: "kl37",
  //   equipe2: "Os Revolucionários",
  //   senha2: "mn48",
  // },
  // {
  //   escola: "Colégio Sorocaba",
  //   email: "anaquezia.ferraz@colegiosorocaba.com.br",
  //   equipe1: "Equipe 3",
  //   senha1: "qr36",
  //   equipe2: "A Tropa do Enigma",
  //   senha2: "op25",
  // },
  // {
  //   escola: "Colégio Monteiro Lobato",
  //   email: "contato@colegiomlobato.com.br",
  //   equipe1: "Monteiro 1",
  //   senha1: "kl77",
  //   equipe2: "Monteiro 2",
  //   senha2: "mn88",
  // },
  // {
  //   escola: "Escola Pilar",
  //   email: "thiara@pilarjarinu.com.br",
  //   equipe1: "Júpiter",
  //   senha1: "ef03",
  //   equipe2: "Mercúrio",
  //   senha2: "gh15",
  // },
  // {
  //   escola: "COLÉGIO GRADUAL TIETÊ",
  //   email: "coordenacao@colegiogradual.com.br",
  //   equipe1: "GRADUAL",
  //   senha1: "st56",
  //   equipe2: "",
  //   senha2: "",
  // },
  // {
  //   escola: "Colégio Alpis Veredas",
  //   email: "protiagobarros@gmail.com",
  //   equipe1: "Alpis Veredas 1",
  //   senha1: "mn22",
  //   equipe2: "Alpis Veredas 3",
  //   senha2: "op33",
  // },
  // {
  //   escola: "Anjo da Guarda São Rafael",
  //   email: "tdiasm@gmail.com",
  //   equipe1: "FERNANDA METÁLICA",
  //   senha1: "ab12",
  //   equipe2: "ONÇA PINTADA",
  //   senha2: "cd34",
  // },
  {
    escola: "Colégio e Curso Conexão",
    email: "coordenacao@colegioecursoconexao.com.br",
    equipe1: "Liga X",
    senha1: "ef23",
    equipe2: "",
    senha2: "",
  },
  // {
  //   escola: "ESCOLA INTERATIVA",
  //   email: "sandrapmancini@gmail.com",
  //   equipe1: "NEURÔNIOS EM AÇÃO",
  //   senha1: "ab81",
  //   equipe2: "",
  //   senha2: "",
  // },
  // {
  //   escola: "Colégio Associação de Ensino Guararapes",
  //   email: "crisgrp@hotmail.com",
  //   equipe1: "Araucária",
  //   senha1: "qr44",
  //   equipe2: "Aroeira",
  //   senha2: "st55",
  // },
  // {
  //   escola: "Colégio Oficina do Estudante",
  //   email: "direcaocolegio@oficinadoestudante.com.br",
  //   equipe1: "Equipe - Brasil",
  //   senha1: "op99",
  //   equipe2: "Equipe Paineiras",
  //   senha2: "qr00",
  // },
  // {
  //   escola: "Colégio Batista de Santarém",
  //   email: "maria_dasgracas35@hotmail.com",
  //   equipe1: "Amarelo",
  //   senha1: "wx77",
  //   equipe2: "Verde",
  //   senha2: "yz88",
  // },
  // {
  //   escola: "Colégio Carlos Drummond de Andrade",
  //   email: "coordenacao03@ccda.com.br",
  //   equipe1: "Lirius",
  //   senha1: "uv82",
  //   equipe2: "Girassol",
  //   senha2: "wx93",
  // },
  // {
  //   escola: "CENTRO EDUCACIONAL CRISTÃO",
  //   email: "GUILHERMECARMELLO@COLEGIOCEDUC.COM.BR",
  //   equipe1: "The Thundermans",
  //   senha1: "kl11",
  //   equipe2: "Curimbatá",
  //   senha2: "ef38",
  // },
  // {
  //   escola: "Colégio Luminous Sol",
  //   email: "marcela.braganholo@gmail.com",
  //   equipe1: "Soul",
  //   senha1: "ef44",
  //   equipe2: "Ilumina",
  //   senha2: "cd33",
  // },
  // {
  //   escola: "COLÉGIO PROFESSOR ANTÔNIO BARROS",
  //   email: "guilherme.vasconcelos@pabescola.com.br",
  //   equipe1: "ELITE",
  //   senha1: "uv24",
  //   equipe2: "",
  //   senha2: "",
  // },
  // {
  //   escola: "Teresa de Calcutá",
  //   email: "cris.golz@terra.com.br",
  //   equipe1: "Menos é menos",
  //   senha1: "op59",
  //   equipe2: "Brain",
  //   senha2: "qr60",
  // },
  {
    escola: "Colégio Sistema",
    email: "sec@colsistema.com.br",
    equipe1: "Arara-Azul",
    senha1: "kl02",
    equipe2: "Onça-Pintada",
    senha2: "mn14",
  },
  // {
  //   escola: "Instituto Educacional Coração de Maria",
  //   email: "canal.coordenacao@iecoracaodemaria.com.br",
  //   equipe1: "Instituto Educacional Coração de Maria 2025",
  //   senha1: "ij26",
  //   equipe2: "",
  //   senha2: "",
  // },
  // {
  //   escola: "Colégio Primar",
  //   email: "katiajoyceguedes@hotmail.com",
  //   equipe1: "Decifradores Primar",
  //   senha1: "st13",
  //   equipe2: "",
  //   senha2: "",
  // },
  // {
  //   escola: "COLÉGIO PURIFICAÇÃO",
  //   email: "mj-oliveira2012@hotmail.com",
  //   equipe1: "OS GREGOS",
  //   senha1: "yz46",
  //   equipe2: "OS ROMANOS",
  //   senha2: "ab57",
  // },
  // {
  //   escola: "Oliveira Ferreira",
  //   email: "prof.valdirsantos@gmail.com",
  //   equipe1: "COF",
  //   senha1: "st71",
  //   equipe2: "",
  //   senha2: "",
  // },
  // {
  //   escola: "Colégio ENAU",
  //   email: "coordenacao.enau@colegioenau.com.br",
  //   equipe1: "Oráculo do Etapa",
  //   senha1: "gh45",
  //   equipe2: "Mestres do Enigma",
  //   senha2: "ij67",
  // },
  // {
  //   escola: "Colégio Integrado Belém Ltda",
  //   email: "yussefayan@colegioin.com",
  //   equipe1: "MUNDURUKU",
  //   senha1: "ab22",
  //   equipe2: "TUPINAMBÁS",
  //   senha2: "yz11",
  // },
  // {
  //   escola: "Colégio Iguatemy",
  //   email: "everton.jose@iguatemy.com.br",
  //   equipe1: "Decifraloucos",
  //   senha1: "uv78",
  //   equipe2: "Os Sherlock",
  //   senha2: "wx90",
  // },
  // {
  //   escola: "Colégio Unisuz",
  //   email: "daniel.fernandez@colegiounisuz.com.br",
  //   equipe1: "Alexandrinos",
  //   senha1: "uv58",
  //   equipe2: "Gambistas",
  //   senha2: "st47",
  // },
  // {
  //   escola: "Colégio Magistra",
  //   email: "magistraprofessores@colegiomagistra.com.br",
  //   equipe1: "Magistrados",
  //   senha1: "ij66",
  //   equipe2: "Nerdolas do Magistra",
  //   senha2: "gh55",
  // },
  // {
  //   escola: "Colégio Santa Marta",
  //   email: "cristinal72@yahoo.com.br",
  //   equipe1: "Half a dozen",
  //   senha1: "ij91",
  //   equipe2: "",
  //   senha2: "",
  // },
  // {
  //   escola: "Colégio Atibaia",
  //   email: "colati@colegioatibaia.com.br",
  //   equipe1: "Athena",
  //   senha1: "uv66",
  //   equipe2: "Os 00",
  //   senha2: "cd27",
  // },
  // {
  //   escola: "COLÉGIO BRASILIS",
  //   email: "raphaelmelo@colegiobrasilis.com.br",
  //   equipe1: "DESAFIADORES DE LIMITES",
  //   senha1: "ab99",
  //   equipe2: "",
  //   senha2: "",
  // },
  // {
  //   escola: "COLÉGIO BRASILIS",
  //   email: "oseias@colegiobrasilis.com.br",
  //   equipe1: "ESQUADRÃO DOS ENIGMAS",
  //   senha1: "cd00",
  //   equipe2: "",
  //   senha2: "",
  // },
];
